# question-1:

In [2]:
import numpy as np
a = np.arange(2,51,3)
print(a)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


# question-2:

In [5]:
l1 = []
l2 = []
for i in range(5):
    e1 = int(input("1st list elements:"))
    l1.append(e1)
    a1 = np.array(l1)
    s1 = np.sort(a1)
    
for i in range(5):
    e2 = int(input("2nd list elements:"))
    l2.append(e2)
    a2 = np.array(l2)
    s2 = np.sort(a2)
    
print(a1)
print(a2)
c = np.concatenate((a1, a2))
cs = np.sort(c)
print(c)
print(s1)
print(s2)
print(cs)

1st list elements:2
1st list elements:3
1st list elements:3
1st list elements:3
1st list elements:2
2nd list elements:2
2nd list elements:3
2nd list elements:3
2nd list elements:2
2nd list elements:3
[2 3 3 3 2]
[2 3 3 2 3]
[2 3 3 3 2 2 3 3 2 3]
[2 2 3 3 3]
[2 2 3 3 3]
[2 2 2 2 3 3 3 3 3 3]


# Question-3:

In [ ]:
n = int(input("enter number of elements in array:"))
a = np.arange(1,n)
print(a.ndim)
print(a.shape)
print(np.size(a))

# Question-4:

In [32]:
d1 = np.arange(1,7)
d2= np.reshape(d1, (2, 3))
print(d1)
print(d2)
a = d1[:,np.newaxis]
a2 = np.expand_dims(a, axis=0)
print(a)
print(a2)
print(a2.shape)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[[1]
  [2]
  [3]
  [4]
  [5]
  [6]]]
(1, 6, 1)


# Question-5:

In [38]:
a = np.arange(1,10)
b = np.arange(21,30)
a1 = np.reshape(a, (3,3))
a2 = np.reshape(b, (3,3))
print(a1)
print(a2)
v = np.vstack((a1, a2))
h = np.hstack((a1, a2))
print(v)
print(h)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[21 22 23]
 [24 25 26]
 [27 28 29]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [21 22 23]
 [24 25 26]
 [27 28 29]]
[[ 1  2  3 21 22 23]
 [ 4  5  6 24 25 26]
 [ 7  8  9 27 28 29]]


# Question-6:

In [42]:

l = []
n = int(input("enter number of elements in array:"))
for i in range(n):
    x = int(input("element"))
    l.append(x)
print(l)
u = np.unique(l)
print(u)

enter number of elements in array:6
element1
element12
element13
element1
element12
element13
[1, 12, 13, 1, 12, 13]
[ 1 12 13]
